apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque # Or kubernetes.io/dockerconfigjson etc.
data:
  # Base64 encoded values
  # To encode: echo -n 'your_db_username' | base64
  # To encode: echo -n 'your_db_password' | base64
  username: cG9zdGdyZXM= # Replace with base64 encoded username
  password: cGFzc3dvcmQ= # Replace with base64 encoded password
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
stringData: # Use stringData for convenience, K8s will base64 encode it internally
  jwt-secret: eW91ci0yNTYtYml0LXNlY3JldC1rZXktZm9yLWp3dC1zaWduaW5nLTEyMzQ1Njc4OTBhYmNkZWY= # Replace with your actual secret